### ISSUE TITLE
need bf707 supported gcc to compile

### ISSUE THREAD

**Issue by benolayinka** [DAB-Embedded/adi-bf707-uboot#1]
Is source available somewhere to compile gcc with blackfin+ support? how did you compile u boot?

**Comment by astaliarou** [comment]
https://blackfin.uclinux.org/doku.php?id=bootloaders:u-boot:compiling
board config: bf707-ezkit

**Comment by benolayinka** [comment]
Haha thank you, I still feel the instructions can be a little confusing for
a beginner, but here was my process for anyone else who it might help.
First tried just "make" in your adi-bf707-uboot repo

make

Makefile:487: *** "System not configured - see README".  Stop.

So I go through the readme and it looks like I need to make the
configuration file.
After trying to "make" several cpu architectures..

make blackfin+_config

make: *** No rule to make target `blackfin+_config'.  Stop.

make: *** [blackfin+_config] Error 1


make blackfin_config

make: *** No rule to make target `blackfin_config'.  Stop.

make: *** [blackfin_config] Error 1

So I guess that the makefiles are based on boards (why not CPU
architectures?), and I get

make bf707-ezkit_config

Configuring for bf707-ezkit board...

make

make: bfin-uclinux-gcc: Command not found

/bin/sh: bfin-uclinux-gcc: command not found


Should I use the ADI Blackfin Toolchain gcc, which only supports BF50X
boards? I'm kind of back where I started, right? I don't have a version of
gcc designed to compile on the BF707

Am Fr., 22. Feb. 2019 um 23:05 Uhr schrieb astaliarou <
notifications@github.com>:

**Comment by astaliarou** [comment]
https://files.fm/f/a3y57rj4

**Comment by benolayinka** [comment]
> https://files.fm/f/a3y57rj4

Sweet this is exactly what I was hoping for, thank you! Why isn't it up on github?

**Comment by astaliarou** [comment]
This is binary, not sources.
